import TipoCambio from "../assets/TipoCambio.png"
import ISI from "../assets/ISI.png"

export const Unidad5 = () => {
    const estiloTexto = {
        overflow: 'hidden',
        wordWrap: 'break-word',
        whiteSpace: 'pre-wrap'
    };

    return (
        <>
            <div class="accordion" id="accordionPanelsStayOpenExample">
                <div class="accordion-item">
                    <h2 class="accordion-header">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
                            Clase Nº 1: Modelo Agroexportador (1880-1930) I
                        </button>
                    </h2>
                    <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse">
                        <div class="accordion-body" style={estiloTexto}>
                            <h6>Argentina Colonial</h6>
                            <p>La etapa colonial se caracterizaba por el comercio mercantilista entre la corona española y sus colonias en América. Básicamente los españoles traían productos manufacturados y a cambio se llevaban productos de la agricultura tropical y minerales. La argentina por esos tiempos era un territorio muy vasto y escasamente poblado. Debido a la inexistencia de vías de comunicación (no existían muchas rutas transitables) la poca población existente estaba escasamente integrada: había economías de subsistencia en distintas regiones e intercambio en pequeños mercados locales. </p>
                            <p>Si bien en 1816 se produce la independencia Argentina de España, no será sino hacia 1860 que se produce un cambio en la estructura productiva desde el modelo colonial al modelo agroexportador. Pero el hecho a destacar es que dicho cambio no va a ser promovido endógenamente por el gobierno nacional, sino que será consecuencia (efecto) de cambios que se van a producir en el plano de la economía internacional.</p>
                            <h6>Cambios en el comercio mundial</h6>
                            <p>Hacia mediados del siglo XIX, Europa es un continente eminentemente rural (más del 70% de la población vive en el campo). Parte de la población se dedica a la producción de manufacturas y al comercio. Estos comerciantes, con el afán de tener mejores ganancias, ampliaban territorialmente sus mercados con la finalidad de vender más y por lo tanto tener mayores ganancias. Conforme aumentaba el comercio, aumentaba simultáneamente la rivalidad entre los comerciantes por apropiarse de una porción mayor de mercado. Dicha competencia impulsó a muchos de estos comerciantes a ver la forma de ofrecer los productos a un precio menor que sus competidores, lo que los llevó a una carrera por generar invenciones que aplicadas al proceso productivo les permitiese producir más cantidad de mercancías por jornada de trabajo, lo que les permitiría ofrecer cada una a un precio menor. Este conjunto de innovaciones técnicas aplicadas al proceso productivo, que permite a los productores aumentar la productividad del trabajo es lo que mundialmente se dio a conocer como Revolución industrial.</p>
                            <h6>Efecto de la Revolución industrial en la estructura productiva de los países europeos</h6>
                            <p>Estas innovaciones llevadas a la producción en el campo (agro) y en la industria generaron dos efectos bien marcados. Por un lado les permitió a los productores llevar una mayor cantidad de bienes al mercado (reemplazar un trabajador por una máquina le permite al empresario tener una producción total mayor en término de unidades fabricadas al término de una jornada de trabajo). Por otro lado si antes necesitaba 10 empleados para producir 100 unidades de un bien, ahora aplicando la innovación técnica (maquinaria) sólo necesito 5 empleados para producir al final de la misma jornada 100 unidades de dicho bien, por lo tanto aquí suceden dos cosas: 1) los otros 5 trabajadores se quedan sin empleo y pasan a engrosar las filas de la marginalidad y la pobreza y 2) los empresarios aumentan sus ganancias (porque simultáneamente producen más bienes y tienen menos costos salariales).</p>
                            <p>Los ingresos extra que ahora tienen los empresarios no van a ir a parar a la compra de más cantidad de alimentos (la elasticidad ingreso de la demanda por estos bienes es baja), es decir que la cantidad de alimentos que compran no aumenta tanto al aumentar sus ingresos (incluso podríamos pensar que se mantiene constante) por lo que ese ingreso extra va a ir a parar al consumo de otros bienes manufacturados (pensemos: si me pagan $10.000 de sueldo, consumo 5.000 de alimentos y 5.000 de manufacturas. Pero si me aumentan el sueldo a 50.000 probablemente consuma 7.000 o 10.000 en alimentos, pero lo que es seguro es que el gasto en manufacturas va a crecer más que proporcionalmente al aumento en el consumo de alimentos. De este modo es más probable que pase de gastar 5.000 en manufacturas a 30.000 porque me compro algún celular, alguna moto, un Smart TV, etc.). </p>
                            <p>Al generarse una demanda mayor por manufacturas (cambia la estructura de la demanda al cambiar los ingresos) paulatinamente se va a ir produciendo un corrimiento en Europa desde la producción de alimentos hacia la producción de manufacturas (productos industriales). Muchos de los trabajadores rurales expulsados del campo van a pasar a ser obreros industriales, pero muchos otros no se van a poder adaptar o generar condiciones de empleabilidad en dicho sector por lo que, como dijimos antes, van a pasar a ser población urbano-marginal en las grandes ciudades. </p>
                            <p>Europa, al especializarse en la producción de manufacturas va a delegar a los países coloniales del nuevo continente (Argentina) la producción de alimentos para su abastecimiento. De este modo queda establecida la división internacional del trabajo: por un lado Argentina va a producir y exportar alimentos a Europa y Europa va a producir y exportar manufacturas a Argentina. </p>
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
                            Clase Nº 2: Modelo Agroexportador (1880-1930) II
                        </button>
                    </h2>
                    <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse">
                        <div class="accordion-body" style={estiloTexto}>
                            <p>La Revolución industrial permitió el desarrollo económico de los países europeos y su especialización en la producción industrial. Al mismo tiempo, incorporó a Argentina a la órbita del comercio mundial como productor de alimentos, obturando la posibilidad de que posteriormente se transforme en una economía industrial pujante. </p>
                            <p>El éxito de la economía nacional dependía exclusivamente de la compra por parte de los países extranjeros de la producción de alimentos. Y la compra de alimentos por parte de estos países dependía de la fase del ciclo económico que estuviesen atravesando: de este modo, cuando a los países desarrollados les iba bien (producían y generaban ingresos) compraban alimentos a Argentina, esta generaba ingresos y prosperaba. Pero cuando a estos países les iba mal (contraían su producción y se veían reducidos sus ingresos) no compraban a Argentina y ésta, al no poder vender, no generaba ingresos y caía en recesión. En otras palabras, la Argentina era por ese entonces un país cuyo éxito económico estaba atado a los vaivenes de la economía internacional, muy vulnerable a los shocks externos. </p>
                            <h6>Argentina ante la posibilidad del crecimiento económico</h6>
                            <p>En este contexto internacional, Argentina estaba ante la posibilidad de encarar un proceso de desarrollo económico: los países europeos estaban dispuestos a comprarles alimentos y por otra parte existía una vasta zona de tierras fértiles para asentar los cultivos. Sin embargo, para aprovechar la oportunidad de negocios que le ofrece el mercado externo debía resolver varios aspectos. En primer lugar, si bien había una gran zona cultivable, prácticamente al no haber población no había brazos para labrar y cultivar la tierra. Por tal motivo, el gobierno nacional favoreció los procesos migratorios (un promedio anual de 1,5 millones de personas en 1914). Por otro lado, como describimos en la etapa colonial, no había vías de comunicación que integraran las dispersas poblaciones del interior del país con Buenos Aires, por lo que el gobierno nacional promovió la instalación de empresas de capitales ingleses para la construcción de vías férreas, que a través del ferrocarril, fueron conectando las vastas tierras del interior con el puerto de buenos aires, lo que le permitió al país en su conjunto abaratar los costos de transporte. La  red de tendido de vías férreas era de 10 km en 1857, de 6700 km en 1887 y de 35.500 km en 1914. Otro problema que tuvo que enfrentar la Argentina fue la inversión en infraestructura (carreteras, edificios gubernamentales, puertos) para mejorar la fluidez del comercio internacional, para ello tuvo que recurrir al endeudamiento internacional (proveniente principalmente de Inglaterra).</p>
                            <p>Los países europeos, principalmente Inglaterra colaboraron con esta transformación en Argentina más por beneficio propio que por la prosperidad de Argentina. La lógica de incorporación de nuestro país a la órbita del comercio internacional obedeció a cumplir varios objetivos. El primero fue hacer de Argentina una fuente de provisión de alimentos y materias primas a un precio bajo. En segundo lugar, que argentina sea mercado para los bienes industrializados que producen. Y en tercer lugar, otorgar a argentina créditos (financiamiento) para que se desarrolle la infraestructura para cumplir los primeros dos objetivos.</p>
                            <p>La promoción de inversiones inglesas en ferrocarriles por parte del gobierno argentino redundó en grandes beneficios para estos capitales: gozaron de exenciones fiscales, además se les permitió repatriar libremente sus ganancias a sus países de origen. También el gobierno argentino benefició a estas empresas otorgándoles 2 leguas de tierras linderas al tendido férreo que iban construyendo.  Empresas inglesas y estadounidenses instalaron fábricas de tanino en el norte argentino, aserraderos para durmientes y frigoríficos. La inversión se centró en la transformación parcial de materias primas para su exportación y elaboración final en los países de origen. </p>
                            <p>En conclusión, la intervención de los países extranjeros en argentina se basó principalmente en dos fuentes: la instalación en territorio argentino de sus empresas y el otorgamiento de empréstitos para el desarrollo de la infraestructura y el gasto social. </p>
                            <h6>Régimen de tenencia de la tierra: </h6>
                            <p>De la totalidad de los extranjeros que llegaron al país hasta 1914, sólo el 10% de ellos pudo acceder efectivamente a una porción de tierra para la producción agrícola. Hacia 1860, casi la totalidad de las tierras mejores ubicadas y más fértiles ya estaban jurídicamente apropiadas por un puñado de familias acomodadas (este sector es el que históricamente es referenciado como oligarquía terrateniente). </p>
                            <p>La producción agro-exportadora era llevada adelante entonces de 3 formas. Parte de la oligarquía terrateniente explotaba directamente el cultivo en sus extensas tierras, contratando braceros y jornaleros. Otro sector de la oligarquía directamente arrendaba (alquilaba) las tierras para su explotación por terceros. Finalmente los pequeños propietarios explotaban sus tierras directamente para usufructo propio. </p>
                            <p>Este régimen de tenencia de la tierra concentra casi la totalidad de las mismas en unas pocas manos (en 1914, las explotaciones de más de 1000 hectáreas representaban el 8,2% de las explotaciones totales y abarcaban el 79,4% de la superficie total. por su parte, las explotaciones de más de 5000 hectáreas representaban el 1,7% de las explotaciones totales y abarcaban el 49,9% de la superficie total).</p>
                            <p>Como la mayor parte de la producción de alimentos estaba concentrada en unas pocas familias y las ventas no dependían consumo interno sino del consumo internacional, cuanto más pudiesen estas familias comprimir los costos de producción locales (principalmente el salario de los jornaleros) mayor margen de ganancia podrían sacar de las ventas. Esta puja patronal por la baja del salario generó resistencia dentro de la clase trabajadora que se canalizó en una serie de huelgas generales de jornaleros y arrendatarios cuyo episodio más destacado fue el grito de Alcorta, en la provincia de Santa Fe. Estos reclamos buscaban mejorar las condiciones de trabajo, el salario, la jornada y el precio de los arrendamientos.   </p>
                            <p>El régimen de tenencia de la tierra condicionó la distribución de los ingresos en favor de la oligarquía terrateniente y estructuró la demanda en favor del consumo de bienes industriales importados: del ingreso total percibido por este sector, el 40% se destinaba a la compra de bienes industriales de consumo final, el 30% se destinaba a la compra de bienes intermedios y el 30% restante a la adquisición de bienes de capital (maquinarias y equipos). Todo proveniente del exterior. En otras palabras, gran parte del ingreso por la exportación de alimentos volvía al exterior bajo la forma de consumo de bienes importados (esta clase prácticamente no consumía en el mercado doméstico), lo cual no contribuyó al desarrollo del tejido industrial interno. </p>
                            <h6>Estructura y dinámica del modelo</h6>
                            <p>El sector agropecuario ocupaba el 35% de la mano de obra total y representaba el 25% del capital fijo existente. Cuando Argentina exportaba alimentos generaba ingresos, esos ingresos se repartían entre los sectores que los producían (oligarquía, arrendatarios y pequeños propietarios). Como mencionamos en el apartado anterior, gran parte de esos ingresos totales se canalizaban al consumo de bienes importados (el consumo de la oligarquía) pero los pequeños propietarios y los arrendatarios consumían del mercado interno (Bienes de inversión y servicios y productos de la industria liviana: ropa, tejidos, etc.), movilizando en parte la producción nacional en esas áreas y por lo tanto el empleo y los nuevos ingresos, que se vuelven a volcar sobre el mercado interno generando un circulo virtuoso de producción e ingresos que va a ir integrando el tejido industrial local. </p>
                            <p>Ahora bien, cuando los países europeos atraviesan una crisis y suspenden las compras a Argentina, ni oligarquía ni arrendatarios ni pequeños propietarios generan ingresos, por lo tanto los últimos dos no compran en el mercado interno, las empresas no producen y deben echar personal, por lo que el país entra en recesión. </p>
                            <p>En otras palabras, bajo este esquema agro-exportador el desarrollo de la economía nacional se torna sumamente vulnerable y dependiente de los vaivenes de la economía internacional: si a los países europeos les va bien, compran a Argentina, esta genera ingresos y prospera. Cuando a los países europeos les va mal, suspenden las compras a Argentina, ésta pierde sus ingresos y la economía entra en recesión. </p>
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
                            Clase Nº 3:  Modelo de Industrialización por Sustitución de importaciones (1930-1970) I
                        </button>
                    </h2>
                    <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse">
                        <div class="accordion-body" style={estiloTexto}>
                            <h6>El tipo de cambio</h6>
                            <p>El tipo de cambio expresa el valor de una moneda en términos de otra. Cuando pasamos por el banco y vemos la cotización del dólar estamos viendo ni más ni menos que una expresión del tipo de cambio: la expresión Dólar $15 expresa que necesito gastar 15 unidades de la moneda nacional para adquirir 1 (una) unidad de moneda extranjera, en este caso, el dólar. </p>
                            <p>La pregunta que nos podríamos hacer a continuación es de qué depende el valor del tipo de cambio (es decir, por qué 15 y no 10 o 20). Lo primero que debemos decir al respecto es que el valor del tipo de cambio es una decisión política, es decir, que el gobierno fija un régimen que lo determina: el gobierno puede optar por establecer un régimen de tipo de cambio fijo (mantiene el TC a un valor fijo, por ejemplo, no se mueve de $15), un tipo de cambio variable (el gobierno “deja liberado” el valor del TC a la oferta y demanda de moneda extranjera), o un régimen de flotación administrada (el gobierno establece un valor “entre bandas” sobre los que el valor del TC puede variar libremente. Por ejemplo, entre $14 y $16. Si el valor del TC trepa, por la oferta y demanda de dólares, a $17, entonces el gobierno va a intervenir en el mercado para restablecer su valor a un número dentro de esas bandas).</p>
                            <p>Si bien el valor del TC es una decisión política, podemos decir que en definitiva su nivel va a estar condicionado por el balance entre la cantidad de dólares y pesos que exista en la economía a cada momento. Pues la expresión u$1-$15 expresaría que por cada dólar en circulación existen 15 pesos en la economía. Si suponemos constante la cantidad de pesos en la economía, las variaciones en la cantidad de dólares en la economía afectaría el nivel del TC.</p>
                            <p>Básicamente, las principales fuentes de aumento de la cantidad de dólares en un país tienen que ver con las exportaciones (ventas de productos de nuestro país al mundo), las inversiones extranjeras (empresas que deciden invertir en nuestro país) y el endeudamiento externo (los préstamos que otorga el resto del mundo a nuestro país). Entre las fuentes de egreso de dólares del país podemos nombrar entre las principales las importaciones (compras de nuestro país al resto del mundo), las repatriaciones de las ganancias de las empresas extranjeras que operan en el Argentina a sus países de origen y los intereses de la deuda que el país debe pagar a sus acreedores externos por los préstamos otorgados en periodos anteriores.</p>
                            <p>Si aumenta la cantidad de dólares en la economía (por ejemplo por exportaciones), dada la cantidad de pesos existente (que suponemos constante), el tipo de cambio tiende a bajar o, dicho de otro modo, el peso argentino se aprecia respecto al dólar. En este caso, si consideramos como punto de partida un TC a $15 por dólar, en esta nueva situación, el TC “bajaría” a $10 por dólar. ¿Por qué? Sencillamente porque ahora hay en la economía más dólares por pesos que en la situación de partida (Antes había, por ejemplo u$100 y $1500 en la economía, con lo cual la relación es de u$1-$15. Ahora con la entrada de dólares hay u$150 y $1500 en la economía con lo cual la relación cambia a u$1-$10). Ahora cada dólar representa (vale) menos pesos. </p>
                            <p>Si por el contrario disminuye la cantidad de dólares existente en la economía, por ejemplo por efecto de las importaciones, el tipo de cambio va a subir, o dicho de otra forma, el peso se va a depreciar (perder precio). De nuevo, si la situación inicial era de un TC fijado en u$1-$15, es decir que había u$100 y $1500, ahora por efecto de las importaciones hay u$75 y $1500 con lo cual la nueva relación de cambio quedaría en u$1-$20. Ahora cada dólar representa más pesos que antes, es decir, que el peso se deprecia. Gráficamente:</p>
                            <img src={TipoCambio} alt="" />
                            <br />
                            <br />
                            <h6>Agotamiento del modelo agroexportador</h6>
                            <p>Para 1930 ya había un mercado interno bastante desarrollado cuyas demandas no se correspondían a la estructura productiva existente, pues al no haber prácticamente industria nacional dicha demanda se canalizaba en consumo de importaciones. </p>
                            <p>En el año 1929 se produce una crisis mundial con epicentro en Estados Unidos, con efecto sobre la producción y los ingresos de muchos países. El coletazo de la crisis provocó una caída del comercio mundial y un repliegue de los países en defensa del empleo e ingresos en los mismos. </p>
                            <p>Como ya sabemos, el modelo agroexportador dependía para su éxito de las compras que le hacían los países industriales, lo cual tornaba la economía sumamente vulnerable: si a los países industriales les iba bien, le compraban alimentos a Argentina, ésta se hacía de ingresos y el país prosperaba. Por el contrario, si a los países industriales les iba mal, no generaban ingresos y el país entraba en crisis.</p>
                            <p>El episodio de 1929 produce una crisis tan profunda y extendida en el tiempo como nunca antes se había visto.  El efecto de la contracción de los ingresos en los países industriales hacen que éstos dejen de comprar a Argentina alimentos y el país entra en crisis. Además Argentina sigue comprando bienes industriales finales a estos países con lo cual se agudiza el problema del frente externo, al generarse presiones al alza del tipo de cambio (depreciación del peso).</p>
                            <p>Ante este problema, el gobierno argentino intenta morigerar la depreciación del peso actuando sobre el ingreso de mercancías del exterior (importaciones) estableciendo controles de cambios, cuotas de importación, barreras para-arancelarias e incluso la prohibición de ingreso lisa y llanamente. Como resultado de estas acciones, la cantidad de bienes importados disminuye. </p>
                            <p>Tenemos por un lado que la cantidad de bienes importados es menor que antes y además, que lo poco que ingresa se comercializa internamente a un precio mayor (debido a la depreciación del peso). Por ejemplo: Si antes ingresaban 100 unidades de un bien a valor u$1 cada uno. Con un TC inicial de u$1-$15, cada unidad se comercializa en nuestro país a $15. Pero luego de la depreciación del peso y las medidas restrictivas del gobierno a las importaciones tenemos que en lugar de 100 unidades ingresan sólo 50 a valor u$1 cada una. Pero como el TC cambió de u$1-$15 a u$1-$20 ahora cada bien se comercializa en nuestro país a un precio más alto que antes, a $20. Ahora si la demanda interna era de 100 unidades y ahora sólo entran 50, hay una demanda insatisfecha, eso sumado a que el precio del bien es más alto ahora ($20) va a generar las condiciones que alientan a los empresarios locales a producir internamente estos bienes industriales que antes se importaban. Este proceso que se va a ir dando paulatinamente es lo que se ha dado en conocer como Industrialización por Sustitución de Importaciones (ISI).</p>
                            <p>La producción local de estos bienes industriales que antes se importaban tiene ex – ante, algunas ventajas. La primera es que al dejar de comprar afuera estos bienes, el país se ahorra divisas (dólares). En segundo lugar, al producir localmente se genera empleo en el país, ese ingreso se traduce en demanda y esa demanda se traduce en más producción en el resto de las industrias. Por ejemplo: si se instala una fábrica de producción de radios se van a tomar 100 operarios, cada uno de ellos cobra un sueldo. El sueldo de esos operarios se traduce en demanda de bienes y servicios. Si estos 100 empleados utilizan el 10% de su sueldo para comprar galletas, el fabricante de galletas enfrenta una demanda mayor, por lo que tendrá que producir más, contratar más empleados y pagarles un sueldo. De nuevo, este sueldo de los empleados de la fábrica de galletas se va a traducir en nueva demanda. Se produce en la economía de este modo un círculo virtuoso de producción e ingresos que progresivamente va a ir integrando en entramado productivo nacional.   </p>
                        </div>
                    </div>
                </div>


                <div class="accordion-item">
                    <h2 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseFour" aria-expanded="true" aria-controls="panelsStayOpen-collapseFour">
                            Clase Nº 4: Modelo de Industrialización por Sustitución de importaciones (1930-1970) II
                        </button>
                    </h2>
                    <div id="panelsStayOpen-collapseFour" class="accordion-collapse collapse">
                        <div class="accordion-body" style={estiloTexto}>
                            <h6>El papel de las empresas extranjeras en la producción industrial nacional</h6>
                            <p>Dada la restricción impuesta por el gobierno nacional a la importación de bienes industriales finales, los países industriales van a optar por instalar las fábricas en territorio argentino y producir en suelo local lo que antes producían en sus países de origen “sorteando” de este modo dicha restricción. Así, estos países se aseguran de mantener la cuota de mercado en Argentina, cubrir la demanda local, generar utilidades y repatriar las mismas a sus países de origen. </p>
                            <p>Las industrias en las que estos capitales extranjeros van a operar son las más dinámicas del entramado productivo, las de mayor valor agregado e intensivas en ciencia y técnica (la industria automotriz, electromecánica, electrónica, etc.). Las industrias tradicionales van a quedar a cargo del empresariado nacional (indumentaria y calzado, agroindustria, etc.), que son las que poseen menor valor agregado, menor componente tecnológico y por lo tanto menor margen dentro del espectro de las actividades industriales.</p>
                            <p>Las empresas extranjeras van a dominar el 97% de la industria automotriz, el 70% de la industria electrónica, el 80% de la producción de neumáticos, el 80% de la producción de fármacos, etc. Lo cual refleja el peso específico de este tipo de empresas en sectores de alto valor agregado. </p>
                            <p>El lector atento podría preguntarse por qué las empresas extranjeras controlan, bajo este esquema, la producción industrial en Argentina en sus ramas más dinámicas y no los empresarios locales. Para contestar esta pregunta debemos ver primero el papel del cambio técnico (las innovaciones) sobre la división internacional del trabajo en función de la  especialización intra-industrial de los mismos.</p>
                            <h6>El rol del cambio tecnológico</h6>
                            <p>El cambio tecnológico (una innovación tecnológica), como por ejemplo como lo fue el Microchip dio lugar a un gran número de bienes nuevos. Las computadoras, televisores, lavarropas y demás productos no hubiesen visto la luz de no ser por la existencia de esta innovación. Pero para que un país pueda lograr inventar el Microchip previamente tuvo que realizar una enorme inversión en formación de científicos, laboratorios, inversión en muchos proyectos fallidos (ensayo y error) y luego de varios años y de una enorme inversión se producen algunos resultados, como por ejemplo el Microchip. Ahora bien, no todos los países están dispuestos a invertir en innovación tecnológica (la producción de nuevos bienes intensivos en ciencia y técnica) o tienen otras prioridades (sociales, de infraestructura básica, vivienda, servicios básicos, etc.) que resolver previamente. Por lo que al ser muy pocos los países que disponen de estos bienes, los precios de los mismos son elevados. Además, la organización mundial de comercio (OMC) a través de tratados y resoluciones protege a través de Patentes el usufructo exclusivo de dicha tecnología al país productor a fin de que se recuperen las inversiones realizadas. A partir de la segunda guerra mundial, una parte de los países del mundo (principalmente Estados Unidos, Alemania y Japón) van a pasar a ser la vanguardia en la producción de bienes intensivos en tecnología especializándose en la producción de este tipo de bienes. De este modo, se establece una nueva división internacional del trabajo entre los mismos países desarrollados: por un lado algunos van a producir bienes con alto contenido tecnológico y otros seguirán produciendo bienes industriales con un contenido tecnológico menor. </p>
                            <h6>Especialización intra-industrial entre los países</h6>
                            <p>Supongamos que para la producción de una radio se precisan tres etapas: la producción de los microchips, la producción de los componentes plásticos de la radio (la carcasa) y finalmente el ensamblado de los primeros dos procesos. Pensemos que cada etapa en la producción de esta radio está repartida en tres países diferentes. La incidencia del costo en el precio final de la radio del país que produce los microchips, al ser el único que posee dicha tecnología va a ser más alto que la incidencia del costo del país que produce los componentes plásticos (porque esa tecnología está más difundida en el mundo, muchos países tienen esa tecnología al alcance) y finalmente la incidencia del costo del ensamblado en el precio final va a ser la menor, pues no se necesita mucho desarrollo tecnológico para montar ese tipo de fábricas, Gráficamente: </p>
                            <img src={ISI} alt="" />
                            <p>En conclusión, los países que se especializan en la producción de bienes intensivos en ciencia y técnica van a ser los que mayores márgenes de ganancia tienen dentro de la cadena de valor global. Por lo tanto van a ser los países que alcancen un grado de desarrollo superior al resto. </p>
                            <h6>El lugar de la Argentina en la nueva división internacional del trabajo.</h6>
                            <p>En primer lugar, Argentina, así como el resto de los países productores de bienes primarios va a quedar al margen de este comercio intra-industrial que se produce entre los países desarrollados. </p>
                            <p>Como mencionamos anteriormente, el rol de los países industriales en los países sub-desarrollados va a ser la instalación de sus empresas para la explotación del mercado local y no como plataforma para la exportación de bienes industriales finales al resto del mundo. </p>
                            <p>Ante la inexistencia de capital y tecnología disponibles en el mercado local, la principal fuente de cambio tecnológico va a ser la que traen las empresas extranjeras al radicar sus filiales en nuestro país. De este modo, el núcleo más dinámico de la cadena industrial, el que mayor valor agregado posee y por lo tanto el que mayores márgenes de ganancia tienen va a estar en Argentina dominado por empresas extranjeras. </p>
                            <p>Argentina tenía condiciones para desarrollar su industria en forma autónoma pero no lo hizo: el grado de apertura y la composición del comercio exterior (importaba bienes industriales) limitaba el acervo tecnológico y el tamaño del mercado (demanda potencial) sobre el sistema industrial. Inglaterra presenta un ejemplo del caso contrario: Exportaba bienes industriales y por ello el peso de la industria era acrecentado por la composición de su comercio exterior.</p>
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseFive" aria-expanded="false" aria-controls="panelsStayOpen-collapseFive">
                            Clase Nº 5:  Monetarismo y Valorización Financiera (1970-2000)
                        </button>
                    </h2>
                    <div id="panelsStayOpen-collapseFive" class="accordion-collapse collapse">
                        <div class="accordion-body" style={estiloTexto}>

                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseSix" aria-expanded="false" aria-controls="panelsStayOpen-collapseSix">
                            Clase Nº 6: Coyuntura Económica 2001-2023
                        </button>
                    </h2>
                    <div id="panelsStayOpen-collapseSix" class="accordion-collapse collapse">
                        <div class="accordion-body" style={estiloTexto}>
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}